### ISSUE TITLE
python setup.py test yields error

### ISSUE THREAD

**Issue by acpmasquerade** [picovico/python-sdk#22]
```
Installed /tmp/easy_install-AfcQay/mock-2.0.0/pbr-1.9.1-py2.7.egg
Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/tmp/easy_install-AfcQay/mock-2.0.0/pbr-1.9.1-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/tmp/easy_install-AfcQay/mock-2.0.0/pbr-1.9.1-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/tmp/easy_install-AfcQay/mock-2.0.0/pbr-1.9.1-py2.7.egg/pbr/util.py", line 431, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
  File "//home/machine/.virtualenvs/picovico-python-sdk/local/lib/python2.7/site-packages/pkg_resources.py", line 1302, in evaluate_marker
    return cls.interpret(parser.expr(text).totuple(1)[1])
  File "//home/machine/.virtualenvs/picovico-python-sdk/local/lib/python2.7/site-packages/pkg_resources.py", line 1337, in interpret
    return op(nodelist)
  File "//home/machine/.virtualenvs/picovico-python-sdk/local/lib/python2.7/site-packages/pkg_resources.py", line 1250, in atom
    return cls.interpret(nodelist[2])
  File "//home/machine/.virtualenvs/picovico-python-sdk/local/lib/python2.7/site-packages/pkg_resources.py", line 1337, in interpret
    return op(nodelist)
  File "//home/machine/.virtualenvs/picovico-python-sdk/local/lib/python2.7/site-packages/pkg_resources.py", line 1271, in comparison
    raise SyntaxError(msg)
SyntaxError: '<' operator not allowed in environment markers
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-AfcQay/mock-2.0.0/setup.cfg: SyntaxError: '<' operator not allowed in environment markers
```

**Comment by acpmasquerade** [comment]
`$ pip install -U setuptools` solved the issue.
upgraded to version - setuptools 21.0.0
